
trigger: none
#- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: caCertificate
  inputs:
    secureFile: 'azure_id_rsa.pub'
    retryCount: '2'

- task: TerraformInstaller@0
  name: install_TF
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-svc'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'epam-tf-backeng-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'epamtfbackendstorage'
    backendAzureRmStorageAccountSku: 'Standard_LRS'
    backendAzureRmContainerName: 'epamtfbackendcontainer'
    backendAzureRmKey: 'epam-tf-state.tfstate'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var mysql-admin-login=$(mysql-admin-login) -var mysql-admin-password=$(mysql-admin-password)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
    environmentServiceName: 'azure-resource-manager-svc'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var mysql-admin-login=$(mysql-admin-login) -var mysql-admin-password=$(mysql-admin-password)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/infrastructure'
    environmentServiceName: 'azure-resource-manager-svc'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var mysql-admin-login=$(mysql-admin-login) -var mysql-admin-password=$(mysql-admin-password)'
    allowTelemetryCollection: true

- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(7eb18278-1682-4ad9-9148-814e2b6039f9)'
    ServerName: 'zekn-mysql-server.mysql.database.azure.com'
    DatabaseName: 'zekn_mysql_db'
    SqlUsername: '$(mysql-admin-login)@zekn-mysql-server'
    SqlPassword: '$(mysql-admin-password)'
    TaskNameSelector: 'SqlTaskFile'
    SqlFile: '$(System.DefaultWorkingDirectory)/terraform/infrastructure/sql/mysql.sql'
    IpDetectionMethod: 'AutoDetect'
